project:
  type: website
  output-dir: docs

website:
  title: "ipw-selection"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

#pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

# Output options (more information on Jekyll's site)
timezone: "Europe/Oslo"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true
