project:
  type: website
  output-dir: docs

website:
  title: "Johan de Aguas"
  navbar:
    left:
      - href: https://johandh2o.github.io
        text: Home
      - href: https://johandh2o.github.io/blog.html
        text: Blog

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual